#!/usr/bin/env python

Import("env")

core_sources = []

env.add_source_files(core_sources, "*.cpp")

# Build it all as a library
lib = env.add_library("lib_bbcpp", core_sources)
env.Prepend(LIBS=[lib])
