#!/usr/bin/env python

Import("env")

env.core_sources = []

#env.add_source_files(env.core_sources, "*.cpp")

env.add_source_files(env.core_sources, "./trantor/net/inner/poller/*.cc")
env.add_source_files(env.core_sources, "./trantor/net/inner/*.cc")
env.add_source_files(env.core_sources, "./trantor/net/*.cc")


env.core_sources.append("./trantor/utils/AsyncFileLogger.cc")
env.core_sources.append("./trantor/utils/ConcurrentTaskQueue.cc")
env.core_sources.append("./trantor/utils/Date.cc")
env.core_sources.append("./trantor/utils/Logger.cc")
env.core_sources.append("./trantor/utils/LogStream.cc")
env.core_sources.append("./trantor/utils/MsgBuffer.cc")
env.core_sources.append("./trantor/utils/SerialTaskQueue.cc")
env.core_sources.append("./trantor/utils/TimingWheel.cc")

#todo windows build
#env.core_sources.append("./third_party/wepoll/Wepoll.c")
#env.core_sources.append("./trantor/utils/WindowsSupport.cc")

# Build it all as a library
lib = env.add_library("trantor", env.core_sources)
env.Prepend(LIBS=[lib])
