#!/usr/bin/env python

Import("env_mod")

env_mod.core_sources = []

env_mod.add_source_files(env_mod.core_sources, "*.cpp")

# Build it all as a library
lib = env_mod.add_library("message_page", env_mod.core_sources)
env_mod.Prepend(LIBS=[lib])
