#ifndef RBAC_DEFAULT_PERMISSIONS_H
#define RBAC_DEFAULT_PERMISSIONS_H

enum RBACDefaultPermissions {
    RBAC_PERMISSION_CREATE = 1 << 0,
    RBAC_PERMISSION_READ = 1 << 1,
    RBAC_PERMISSION_UPDATE = 1 << 2,
    RBAC_PERMISSION_DELETE = 1 << 3,

    RBAC_PERMISSION_ALL = RBAC_PERMISSION_CREATE | RBAC_PERMISSION_READ | RBAC_PERMISSION_UPDATE | RBAC_PERMISSION_DELETE,
    RBAC_PERMISSION_NONE = 0
};

enum RBACDefaultRankPermissions {
    RBAC_PERMISSION_ADMIN_PANEL = 1 << 0,
};

#endif