#!/usr/bin/env python

Import("env")

env.core_sources = []

env.Append(CPPDEFINES=[ "PLATFORM_LINUX", "DEBUG_ENABLED" ])
env.Append(LIBS=["dl"])

env.add_source_files(env.core_sources, "platform_initializer.cpp")
env.add_source_files(env.core_sources, "./linux/*.cpp")

env.Append(LINKFLAGS=["-static-libgcc", "-static-libstdc++"])

# Build it all as a library
lib = env.add_library("platform", env.core_sources)
env.Prepend(LIBS=[lib])
