#ifndef HTTP_ENUMS_H
#define HTTP_ENUMS_H

enum HTTPMethod {
	HTTP_METHOD_GET = 0,
	HTTP_METHOD_POST,
	HTTP_METHOD_HEAD,
	HTTP_METHOD_PUT,
	HTTP_METHOD_DELETE,
	HTTP_METHOD_OPTIONS,
	HTTP_METHOD_PATCH,
	HTTP_METHOD_INVALID,
};

#endif