#!/usr/bin/env python

Import("env_mod")
Import("env")

env_mod.core_sources = []

env_mod.add_source_files(env_mod.core_sources, "*.cpp")
env_mod.add_source_files(env_mod.core_sources, "drogon/lib/src/*.cc")
env_mod.add_source_files(env_mod.core_sources, "drogon/lib/inc/http/*.cc")
env_mod.add_source_files(env_mod.core_sources, "drogon/lib/src/ssl_funcs/*.cc")

# Build it all as a library
lib = env_mod.add_library("drogon", env_mod.core_sources)
env.Prepend(LIBS=[lib])
