#!/usr/bin/env python

Import("env_mod")
Import("env")

env_mod.core_sources = []

env_mod.add_source_files(env_mod.core_sources, "trantor/net/*.cc")
env_mod.add_source_files(env_mod.core_sources, "trantor/net/inner/*.cc")
env_mod.add_source_files(env_mod.core_sources, "trantor/net/inner/poller/*.cc")

env_mod.add_source_files(env_mod.core_sources, "trantor/utils/AsyncFileLogger.cc")
env_mod.add_source_files(env_mod.core_sources, "trantor/utils/ConcurrentTaskQueue.cc")
env_mod.add_source_files(env_mod.core_sources, "trantor/utils/Date.cc")
env_mod.add_source_files(env_mod.core_sources, "trantor/utils/Logger.cc")
env_mod.add_source_files(env_mod.core_sources, "trantor/utils/LogStream.cc")
env_mod.add_source_files(env_mod.core_sources, "trantor/utils/MsgBuffer.cc")
env_mod.add_source_files(env_mod.core_sources, "trantor/utils/SerialTaskQueue.cc")
env_mod.add_source_files(env_mod.core_sources, "trantor/utils/TimingWheel.cc")

#windows only
#env_mod.add_source_files(env_mod.core_sources, "third_party/wepoll/*.c")
#env_mod.add_source_files(env_mod.core_sources, "trantor/utils/WindowsSupport.cc")

# Build it all as a library
lib = env_mod.add_library("trantor", env_mod.core_sources)
env.Prepend(LIBS=[lib])
